'use strict';
(() => {
const C=window.CASE, $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SAVE_KEY='white-oak-detective-demo-v1';
const fresh=()=>({version:1,phase:'hub',room:'hall',introStep:0,collected:[],asked:{},unlocked:{},hinted:[],dogUses:0,labDone:false,report:{suspect:null,weapon:null},notes:'',stars:[],endingStep:0,solved:false});
let state=fresh(), saved=null, overlay=null, showSpots=false, highlighted=null, notebookTab='items', compareA='',compareB='',lastFocus=null,toastTimer, saveAvailable=true;
try {const raw=localStorage.getItem(SAVE_KEY);if(raw){saved=JSON.parse(raw);if(saved.version!==1||!Array.isArray(saved.collected)||!C.rooms[saved.room])saved=null;}}catch{saveAvailable=false;}
const app=$('#app'),overlayRoot=$('#overlay-root');
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));saved=JSON.parse(JSON.stringify(state));}catch{saveAvailable=false;}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function person(id,cls=''){const p=C.people[id];return `<div class="portrait portrait-${p.portrait} ${cls}" role="img" aria-label="${p.name}像素半身像"></div>`;}
function button(label,action,value='',cls=''){return `<button class="${cls}" data-action="${action}"${value!==''?` data-value="${esc(value)}"`:''}>${label}</button>`;}
function head(mode='game'){return `<header class="topbar"><div class="brand"><span class="brand-mark" aria-hidden="true">⌕</span><div><h1>${C.title}</h1><small>白栎庄园 · CASE FILE 001</small></div></div><div class="top-actions"><span class="save">${saveAvailable?'进度自动保存':'当前浏览器无法保存进度'}</span>${mode==='game'?button('笔记 <span class="gold">'+state.collected.length+'</span>','notebook')+button('提交报告','report')+button('帮助','help','','quiet'):''}${button('主菜单','menu','','quiet')}</div></header>`;}
function render(){
 if(state.phase==='title')return title();
 if(state.phase==='hub')return hub();
 if(state.phase==='intro')return intro();
 if(state.phase==='ending')return ending();
 if(state.phase==='closed')return conclusion();
 const r=C.rooms[state.room];
 app.innerHTML=head()+`<div class="game"><div class="location-head"><div><div class="eyebrow">WHITE OAK MANOR / ${r.floor}</div><h2>${r.name}</h2></div><span class="tag">11 月 14 日 · 调查中</span></div><div class="play-layout"><nav class="navigation" aria-label="庄园房间"><div class="eyebrow">庄园平面</div>${Object.entries(C.rooms).map(([id,rr],i)=>button(`<span class="room-no">0${i+1}</span>${rr.name}<small>${rr.floor}</small>`,'room',id,'room-button '+(id===state.room?'active':''))).join('')}<div class="nav-bottom">窗外，雨还在下。<br>所有人留在庄园内。</div></nav><section><div class="stage-wrap"><div class="stage ${showSpots?'show-spots':''}" aria-label="${r.name}第一人称场景"><div class="room-art room-${r.art}"></div><div class="atmosphere"></div>${r.spots.map(s=>hotspot(s)).join('')}</div><div class="scene-tools"><small>移动鼠标观察 · 点击物品进入近景</small>${button(showSpots?'隐藏交互位置':'显示交互位置','hotspots')}</div></div><div class="dialogue-bar"><div class="narrative"><div class="eyebrow">现场 / OBSERVATION</div><p>${r.mood}</p></div>${r.person?`<button class="talk-card" data-action="talk" data-value="${r.person}">${person(r.person)}<span><strong>${C.people[r.person].name}</strong><small>交谈 →</small></span></button>`:''}</div></section></div><footer class="game-footer"><div class="dog-button">${button('警犬 · 寻找气味','dog','',state.dogUses>=3?'quiet':'')}<span class="paws">${'◆'.repeat(3-state.dogUses)}${'◇'.repeat(state.dogUses)}</span><span>剩余 ${3-state.dogUses} 次</span></div><div class="controls"><kbd>N</kbd>笔记 <kbd>M</kbd>位置 <kbd>Esc</kbd>返回</div></footer></div>`;
}
function hotspot(s){const [id,label,x,y,w,h]=s;return `<button class="hotspot ${state.collected.includes(id)?'seen':''} ${highlighted===state.room+':'+id?'hinted':''}" style="left:${x}%;top:${y}%;width:${w}%;height:${h}%" data-action="spot" data-value="${id}" aria-label="调查${label}"><span class="diamond"></span><span class="hot-label">${label}</span></button>`;}
function title(){app.innerHTML=`<section class="title-page"><div class="title-copy"><div class="eyebrow">像素侦探 · 第一案</div><h1>未举起的<br>酒杯</h1><p class="tagline">一场尚未开始的晚宴。<br>四个人，各自守着不能说的事。</p><div class="title-buttons">${saved?button('继续调查　→','continue','','primary'):''}${button(saved?'重新开始':'走进事务所　→','new','',saved?'':'primary')}${button('游玩说明','help','','quiet')}</div><div class="title-foot">单人调查 · 自动保存 · DEMO 0.1</div></div><div class="title-art" role="img" aria-label="雨夜的像素侦探事务所"><div class="plate">鹭湾<br><small>2026 年 11 月</small></div></div></section>`;}
function hub(){app.innerHTML=head('hub')+`<div class="game"><div class="location-head"><div><div class="eyebrow">THE DETECTIVE'S OFFICE</div><h2>你的事务所</h2></div><span class="tag">2026.11.14 · 下午</span></div><div class="stage-wrap"><div class="stage show-spots" style="aspect-ratio:16/8"><div class="room-art hub-art"></div><div class="atmosphere"></div>${hotspot(['hubcomputer','电脑',43,38,14,18])}${hotspot(['archive','档案袋',29,42,15,16])}${hotspot(['hubdog','警犬',62,65,26,28])}</div><div class="scene-tools"><small>电脑里有一封新邮件。</small>${button('游玩说明','help')}</div></div><div class="dialogue-bar"><div class="narrative"><div class="eyebrow">事务所 / AFTERNOON</div><p>窗外的雨，没有要停的意思。</p></div></div></div>`;}
function startNew(){state=fresh();save();closeModal();render();}
function goRoom(id){if(!C.rooms[id])return;const old=state.room;state.room=id;closeModal();if(old==='office'&&id!=='office'&&!state.labDone&&['body','cup','water','pillbox','bottle'].every(x=>state.collected.includes(x))){state.labDone=true;state.collected.push('lab');toast('检验记录已返回，已放入笔记。');}save();render();}
function collect(id){if(!C.evidence[id])return false;if(!state.collected.includes(id)){state.collected.push(id);save();toast('已记入笔记：'+C.evidence[id].title);render();return true;}return false;}
function openModal(title,body,{wide=false,compact=false,label='现场记录',after=null}={}){if(!overlay)lastFocus=document.activeElement;overlay={title,after};overlayRoot.innerHTML=`<div class="overlay-backdrop"><section class="modal ${wide?'wide':''} ${compact?'compact':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><div><div class="eyebrow">${label}</div><h2 id="modal-title">${title}</h2></div>${button('×','close','','close-button')}</header><div class="modal-body">${body}</div></section></div>`;setTimeout(()=>overlayRoot.querySelector('input,button,select')?.focus({preventScroll:true}),0);}
function closeModal(){const cb=overlay?.after;overlay=null;overlayRoot.innerHTML='';if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});if(cb)cb();}
function art(id){const e=C.evidence[id];const k=e?.kind||id;let shapes='';const txt=(t,x,y,size=13,fill='#c4bd9a')=>`<text x="${x}" y="${y}" fill="${fill}" font-size="${size}" font-family="monospace" text-anchor="middle">${esc(t)}</text>`;
 const metal='<path d="M135 150h24v-8h17v14h-8v14h-13v-6h-20z" fill="#b4b8a5"/><path d="M140 154h18" stroke="#5d6b69" stroke-width="3"/>';
 const sealLeft='<path d="M48 106h121v8h-9v12h10v10h-9v12h9v10h-122z" fill="#c5c8af"/><path d="M54 139l26-27m3 40 37-40m4 40 28-30" stroke="#476f85" stroke-width="8"/>';
 const sealRight='<path d="M169 106h104v52H170v-10h-9v-12h9v-10h-10v-12h9z" fill="#c5c8af"/><path d="M180 152l38-40m0 40 38-40" stroke="#476f85" stroke-width="8"/>';
 if(k==='bottle'){shapes='<path d="M125 25h70v25h-8v16h15v10h10v128H108V76h10V66h15V50h-8z" fill="#5f351e"/><path d="M125 25h70v24h-70z" fill="#313f3c"/><path d="M118 89h84v94h-84z" fill="#c6b98b"/><path d="M117 74h10v124h-10z" fill="#9a6437"/>'+txt('HX-17',160,115,15,'#32342d')+txt('15–30 min',160,146,12,'#494332')+'<g transform="translate(59,13) scale(.5)">'+sealLeft+'</g>';}
 else if(k==='seal'){shapes='<g transform="translate(-35,-10) scale(1.25)">'+sealRight+'</g>'+txt('01 / 纸篓内',160,211,12);}
 else if(k==='lock'){shapes='<path d="M50 25h90v43h-15v24h22v24h-26v34h14v52H50z" fill="#725037"/><path d="M74 46h49v84H74z" fill="#a4915b"/><path d="M92 68h18v29H92z" fill="#172426"/><path d="M126 164h43v-22h25v37h-36v14h-32z" fill="#596562"/>'+metal+'<path d="M215 160h12v5h-12zm-20 34h19v6h-19z" fill="#957254"/>';}
 else if(k==='coat'){shapes='<path d="M103 37l29-12 25 28 23-28 30 12 30 73-28 16-8 84H105l-8-84-31-15z" fill="#243b4b"/><path d="M131 27l26 26-29 42-18-42m70-26-23 26 29 42 20-42" fill="#3b5060"/><path d="M89 122l44 18-17 45-46-18z" fill="#405561"/><path d="M100 147l21 6-5 14-22-6" fill="#775b51"/>'+metal;}
 else if(k==='knife'){shapes='<path d="M56 164l127-96 15 16-112 102-30 3z" fill="#b5c0b1"/><path d="M65 179l119-101" stroke="#e4dec0" stroke-width="4"/><path d="M166 60l36 44 10-10-36-44z" fill="#9e793e"/><path d="M186 58l40-35 19 23-39 33z" fill="#574637"/><path d="M203 53l17-16" stroke="#c5a557" stroke-width="6"/>';}
 else if(k==='watch'){shapes='<path d="M125 0h70v240h-70z" fill="#302c2c"/><path d="M91 49h138v142H91z" fill="#9c9c89"/><path d="M102 59h116v120H102z" fill="#081b22"/>'+txt('HEART RATE',160,85,11,'#87b5a3')+txt('18:10   78',160,112,12)+txt('18:18   48',160,134,12)+txt('18:23   --',160,156,12);}
 else if(['phone','email'].includes(k)){shapes='<rect x="89" y="16" width="142" height="208" fill="#303f42"/><rect x="97" y="30" width="126" height="179" fill="#b8c3ba"/><rect x="105" y="44" width="110" height="23" fill="#2d585d"/>'+txt(k==='email'?'DRAFT':'RECORD',160,60,13,'#e6deca')+'<path d="M110 86h88v7h-88zm0 23h100v5H110zm0 18h70v5h-70zm0 18h96v5h-96z" fill="#657c76"/>'+txt(id==='phone'?'00:30':id==='debt'?'2,800,000':id==='reminder'?'18:00':'16:12',160,185,18,'#2b4648');}
 else if(['cup','water','wineglass','wine'].includes(k)){shapes=k==='wine'?'<path d="M146 20h28v60l20 20v109h-69V100l21-20z" fill="#314d36"/><path d="M125 124h69v50h-69z" fill="#bea978"/><path d="M145 18h29v28h-29z" fill="#7c673d"/>':`<path d="M108 65h104l-12 101-21 16h-39l-21-16z" fill="#78928b" opacity=".5"/><path d="M119 ${k==='cup'?154:120}h82l-4 39-21 18h-33l-19-18z" fill="${k==='wineglass'?'#995a3e':k==='cup'?'#cabda0':'#82a4a0'}" opacity=".7"/><path d="M108 65h104v7H108zm46 116h12v24h-12zm-27 25h66v6h-66" fill="#bec5ac"/><path d="M119 78h6v65h-6" fill="#d1d2b1"/>`;}
 else if(k==='pills'){shapes='<rect x="39" y="83" width="242" height="86" fill="#96a093"/>'+[0,1,2,3,4,5].map(i=>`<rect x="${45+i*39}" y="91" width="31" height="67" fill="#546b63"/>${i!==4?`<rect x="${53+i*39}" y="116" width="16" height="9" fill="#ddd6b3"/>`:''}`).join('')+txt('18:00',160,201,18);}
 else if(k==='stand'){shapes='<path d="M60 155h200v17H60zM85 126h8v29h-8zm142 0h8v29h-8z" fill="#936e42"/>'+txt('短刀',160,193,14);}
 else if(k==='safe'){shapes='<path d="M66 43h188v158H66z" fill="#65706b"/><path d="M77 53h165v137H77z" fill="#263c43"/><path d="M106 94h15v58h-15z" fill="#c2a666"/><path d="M161 81h57v62h-57z" fill="#101f26"/>'+[0,1,2].map(row=>[0,1,2].map(col=>`<rect x="${169+col*14}" y="${91+row*14}" width="7" height="7" fill="#d5b778"/>`).join('')).join('');}
 else if(k==='case'){shapes='<path d="M54 73h211v120H54z" fill="#4f5042"/><path d="M64 83h191v100H64z" fill="#b6a685"/><path d="M77 88h77v89H77z" fill="#435d50"/><path d="M165 104h74v68h-74z" fill="#ddd0ad"/><path d="M64 192h191v14H64zM133 54h46v19h-9V62h-28v11h-9z" fill="#7d744d"/>';}
 else if(k==='drawing'){shapes='<path d="M51 24h218v190H51z" fill="#d8c7a0"/><path d="M102 120l55-53 59 53z" fill="#9c6348"/><path d="M111 120h91v65h-91z" fill="#bc9d60"/><path d="M147 143h24v42h-24z" fill="#6a8b7b"/>'+txt('给周叔',208,204,16,'#705c43');}
 else if(k==='calendar'||k==='june'){const month=k==='june'?'06':'11',day=k==='june'?'17':'14';shapes='<path d="M70 34h180v174H70z" fill="#d4c49b"/><path d="M70 34h180v37H70z" fill="#765849"/>'+txt(month+' / 2026',160,60,18,'#ece0bd')+txt(day,160,149,66,'#444839')+'<ellipse cx="160" cy="126" rx="61" ry="56" fill="none" stroke="#9e5a3e" stroke-width="4"/>'+txt(k==='june'?'六月':'月日四位',160,193,14,'#66543c');}
 else if(k==='collage'||k==='frame'){return `<div class="evidence-art"><div style="display:flex;border:12px solid #96713d;box-shadow:0 0 0 4px #4e4131;transform:rotate(-4deg);height:80%;position:relative">${person('su')}${person('victim')}${k==='collage'?`<div style="position:absolute;width:50%;height:100%;right:-3px;top:-5px;transform:rotate(6deg);border:3px solid #c3b287;overflow:hidden">${person('butler')}</div>`:''}</div><span class="art-note">${k==='collage'?'PHOTO / 02':'PHOTO / 01'}</span></div>`;}
 else if(k==='body'){return '<div class="evidence-art"><div class="room-art room-1" style="background-size:360% 540%;background-position:86% 0"></div><span class="art-note">现场 / 原位记录</span></div>';}
 else{const title=k==='dna'?'鉴定意见':k==='lab'?'检验记录':k==='student'?'学生证':k==='invitation'?'INVITATION':e?.title||'文件';return `<div class="evidence-art"><div class="paper-object">${esc(title)}<div style="height:45px;margin-top:12px;background:repeating-linear-gradient(transparent 0 13px,#857c5e80 13px 15px)"></div><em>${k==='dna'?'周启明 / 凌知夏':k==='student'?'2004.06.17':k==='invitation'?'2026.11.14 · 19:00':'白栎庄园 · 摘录'}</em></div><span class="art-note">DOCUMENT</span></div>`;}
 return `<div class="evidence-art"><svg viewBox="0 0 320 240" role="img" aria-label="${esc(e?.title||id)}近景" shape-rendering="crispEdges">${shapes}</svg><span class="art-note">${e?C.rooms[e.room].name:'CLOSE UP'}</span></div>`;
}
function inspect(id,back='scene'){const e=C.evidence[id];if(!e)return;collect(id);openModal(e.title,`<div class="inspect-layout"><div>${art(id)}<div class="closeup-footer">${button('放大查看','zoom',id,'quiet')}<small>物品近景</small></div></div><div class="evidence-body"><div class="eyebrow">${C.rooms[e.room].name}</div><h3>${e.title}</h3><p>${esc(e.text)}</p>${e.detail?`<div class="evidence-detail">${esc(e.detail)}</div>`:''}</div></div><div class="inspect-actions"><small>已记入笔记${['body','cup','water','pillbox','bottle'].includes(id)?' · 已登记采样':''}</small><div class="row">${button(state.stars.includes(id)?'★ 已标记':'☆ 标记','star',id)}${button('返回','inspectback',back)}</div></div>`);}
function visitSpot(id){if(highlighted===state.room+':'+id)highlighted=null;
 if(id==='hubcomputer')return hubComputer();
 if(id==='archive')return openModal('历史案件',state.solved?`<div class="eyebrow">已归档 / CASE FILE 001</div><h3 class="gap">未举起的酒杯</h3><p class="gap">白栎庄园 · 2026年11月14日</p><div class="row gap">${button('查看结案记录','caseconclusion','','primary')}${button('重看复盘','replay')}</div>`:'<p>这里暂时没有可查阅的案件。</p><p class="muted gap">完成调查后，报告会放进档案袋。</p>',{compact:true,label:'事务所 / ARCHIVE'});
 if(id==='hubdog')return openModal('警犬',`<p>它抬起头，耳朵动了动。</p><p class="muted gap">每个案件可以请它帮忙寻找气味 3 次。它会带你到一处尚未调查的位置。</p>${button('摸摸它的头','pet','','gap')}`,{compact:true,label:'事务所'});
 if(id==='pot')return openModal('大厅花盆',`<div class="pot-leaves">${button('拨开叶片','leaves','','primary')}</div><p class="muted gap">泥土湿润，叶片遮住了花盆内侧。</p>`,{compact:true});
 if(id==='invitation')return openModal('窗边矮柜',`<div class="file-list">${button('邀请函','inspect','invitation')}${button('桌上日历','inspect','calendar')}</div>`,{compact:true});
 if(id==='computer')return computer();
 if(id==='safe'){collect('safe');return safe();}
 if(id==='clock')return openModal('落地钟','<p>雨声里，钟摆有节奏地摆动。</p><p class="muted gap">晚宴的时间已经过去了。</p>',{compact:true});
 if(id==='flowercalendar')return openModal('墙上日历','<p>一张印着花卉的月历。没有写字。</p>',{compact:true});
 if(id==='uniform')return openModal('衣柜','<p>两件熨平的工作制服。</p>',{compact:true});
 if(id==='phone'&&!state.collected.includes('phone'))return openModal('凌知夏的手机',`<p>“可以看看你的行程吗？”</p><p class="gap gold">凌知夏：“只看行程。”</p>${button('查看行程','inspect','phone','primary gap')}`,{compact:true});
 inspect(id);
}
function hubComputer(){openModal('事务所电脑',`<div class="computer"><div class="computer-head">MAIL / NEWS　　2026.11.14</div><div class="file-list">${button('一封私人邀请 <small>凌维岳 · 白栎庄园 · 今天 19:00</small>','invitationmail')}${button('今日新闻 <small>凌氏慈善基金将举行年度答谢活动</small>','news')}</div></div>`,{label:'事务所 / DESKTOP'});}
function computer(){if(!state.unlocked.computer)return password('computer');openModal('凌维岳的电脑',`<div class="computer"><div class="computer-head">LING / DESKTOP　　11.14</div><div class="file-list">${button('邮件 · 垃圾箱 <small>家庭情况调查　草稿 1</small>','inspect','email')}${button('公司文件 <small>项目结项内部通知</small>','inspect','company')}${button('晚宴安排 <small>11 月 14 日</small>','inspect','agenda')}</div></div>`,{label:'DESKTOP'});}
function safe(){if(!state.unlocked.safe)return password('safe');openModal('保险柜',`<div class="file-list">${button('旧鉴定书复印件','inspect','dna')}${button('一张照片','inspect','collage')}</div>`,{compact:true,label:'柜内物品'});}
function password(which,error=''){openModal(which==='safe'?'保险柜':'电脑已锁定',`<p class="muted">${which==='safe'?'提示：她出生那天，月日四位。':'请输入四位密码。'}</p><form class="password-form" data-lock="${which}"><input class="password-display" aria-label="四位密码" inputmode="numeric" maxlength="4" pattern="[0-9]{4}" autocomplete="off" required placeholder="····"><div class="error" role="status">${error}</div><div class="row">${button('返回','close')}<button type="submit" class="primary">解锁</button></div></form>`,{compact:true,label:'LOCKED'});}
function unlock(form){const which=form.dataset.lock,code=form.querySelector('input').value;if(code===(which==='safe'?'0617':'1114')){state.unlocked[which]=true;save();toast('已解锁');which==='safe'?safe():computer();}else{form.querySelector('.error').textContent='密码不正确。';form.querySelector('input').select();}}
function talk(id,answer='',q=''){const p=C.people[id];openModal('交谈',`<div class="interview">${person(id)}<div><div class="eyebrow">${p.role} · ${p.age} 岁</div><h3 class="speaker">${p.name}</h3><div class="answer">${esc(answer||'……')}</div><div class="statement-label">${q?'询问：'+esc(q)+'　· 已记入口供':'选择一个问题'}</div><div class="questions gap">${C.questions[id].map(([question],i)=>button(question,'ask',id+':'+i,state.asked[id+':'+i]?'asked':'')).join('')}</div><div class="evidence-select"><select aria-label="选择出示的物品" id="show-evidence"><option value="">选择已找到的物品</option>${state.collected.filter(e=>C.evidence[e]).map(e=>`<option value="${e}">${C.evidence[e].title}</option>`).join('')}</select>${button('出示物品','showevidence',id)}</div></div></div>`,{wide:true,label:'口供 / STATEMENT'});}
function ask(value){const [id,index]=value.split(':');const [q,a]=C.questions[id][Number(index)];state.asked[value]={person:id,q,a};save();talk(id,a,q);}
function showEvidence(id){const eid=$('#show-evidence').value;if(!eid)return toast('先选择一件物品。');const a=C.followups[id][eid]||'这件事，我没有要补充的。',q='关于「'+C.evidence[eid].title+'」';state.asked[id+':e:'+eid]={person:id,q,a};save();talk(id,a,q);}
function notebook(tab=notebookTab){notebookTab=tab;const tabs=[['items','物品'],['people','人物'],['statements','口供'],['events','已见事件'],['compare','物品对照'],['notes','我的手记']];let body='';
 if(tab==='items')body=state.collected.length?`<div class="notebook-grid">${state.collected.map(id=>{const e=C.evidence[id];return `<button class="evidence-card" data-action="noteitem" data-value="${id}"><small>${C.rooms[e.room].name}</small>${state.stars.includes(id)?'<span class="star">★</span>':''}<h3>${e.title}</h3><p>${esc(e.text)}</p></button>`;}).join('')}</div>`:'<div class="blank">尚未记录物品。<br>点击房间内的物品进行调查。</div>';
 if(tab==='people')body=`<div class="profile-grid">${Object.entries(C.people).map(([id,p])=>`<div class="profile">${person(id)}<h3>${p.name}</h3><small>${p.age} 岁 · ${p.role}</small><p>${p.bio}</p></div>`).join('')}</div>`;
 if(tab==='statements')body=Object.values(state.asked).length?Object.values(state.asked).map(a=>`<div class="statement"><div><span class="gold">${C.people[a.person].name}</span><div class="small muted gap">${C.people[a.person].role}</div></div><div><div class="question">${esc(a.q)}</div><p>“${esc(a.a)}”</p></div></div>`).join(''):'<div class="blank">尚未记录口供。<br>找到人物，与他们交谈。</div>';
 if(tab==='events')body='<div class="event"><div class="event-time">18:35</div><p>凌承泽上楼。</p></div><div class="event"><div class="event-time">约18:41</div><p>楼上传来撞击声。</p></div><div class="event"><div class="event-time">18:56</div><p>办公室门虚掩，锁口崩裂。凌维岳坐在椅子上。</p></div>';
 if(tab==='compare'){if(!state.collected.length)body='<div class="blank">记录物品后，可以在这里并排查看。</div>';else{if(!state.collected.includes(compareA))compareA=state.collected[0];if(!state.collected.includes(compareB))compareB=state.collected[1]||state.collected[0];const opts=s=>state.collected.map(id=>`<option value="${id}" ${id===s?'selected':''}>${C.evidence[id].title}</option>`).join('');body=`<div class="compare-controls"><select aria-label="左侧物品" data-compare="a">${opts(compareA)}</select><select aria-label="右侧物品" data-compare="b">${opts(compareB)}</select></div><div class="compare-columns">${[compareA,compareB].map(id=>`<section>${art(id)}<h3>${C.evidence[id].title}</h3><p>${esc(C.evidence[id].text)}</p>${C.evidence[id].detail?`<div class="evidence-detail">${esc(C.evidence[id].detail)}</div>`:''}${button('放大查看','zoom',id,'quiet gap')}</section>`).join('')}</div>`;}}
 if(tab==='notes')body=`<p class="selection-hint">这里留给你的判断。内容自动保存。</p><textarea class="notes-area" id="personal-notes" aria-label="我的推理手记" placeholder="写下你的想法……">${esc(state.notes)}</textarea>`;
 openModal('侦探笔记',`<nav class="tabs" aria-label="笔记分类">${tabs.map(([v,t])=>button(t,'notetab',v,v===tab?'active':'')).join('')}</nav>${body}`,{wide:true,label:'NOTEBOOK / 只记录你见到与听到的内容'});
}
function dog(){if(state.dogUses>=3)return toast('它累了。这次案件的寻找次数已用完。');const candidates=[];Object.entries(C.rooms).forEach(([rid,r])=>r.spots.forEach(([id])=>{const key=rid+':'+id;if(state.hinted.includes(key))return;let useful=false;if(id==='pot')useful=!state.collected.includes('bottle');else if(id==='invitation')useful=!state.collected.includes('calendar')||!state.collected.includes('invitation');else if(id==='safe')useful=!state.collected.includes('safe');else if(id==='computer')useful=!state.unlocked.computer;else useful=!!C.evidence[id]&&!state.collected.includes(id);if(useful)candidates.push({rid,id,key});}));if(!candidates.length)return toast('它没有找到新的气味。这次不消耗次数。');const target=candidates[Math.floor(Math.random()*candidates.length)];state.dogUses++;state.hinted.push(target.key);goRoom(target.rid);highlighted=target.key;save();render();toast('警犬停在'+C.rooms[target.rid].name+'的一处位置。');}
function report(){const weapons=state.collected.filter(id=>C.evidence[id]?.weapon);openModal('结案报告',`<div class="eyebrow">白栎庄园 / CASE FILE 001</div><p class="selection-hint gap">把人物与物品拖入对应栏位，也可以直接点击选取。</p><div class="report-slots"><div class="drop-slot" data-slot="suspect"><small>凶手</small><strong>${state.report.suspect?C.people[state.report.suspect].name:'待填写'}</strong></div><div class="drop-slot" data-slot="weapon"><small>凶器</small><strong>${state.report.weapon?C.evidence[state.report.weapon].title:'待填写'}</strong></div></div><div class="small muted">人物</div><div class="report-pool">${['daughter','butler','son','su'].map(id=>`<button draggable="true" data-kind="suspect" data-action="reportpick" data-value="suspect:${id}" class="${state.report.suspect===id?'selected':''}">${C.people[id].name}</button>`).join('')}</div><div class="small muted">已记录的物品</div><div class="report-pool">${weapons.length?weapons.map(id=>`<button draggable="true" data-kind="weapon" data-action="reportpick" data-value="weapon:${id}" class="${state.report.weapon===id?'selected':''}">${C.evidence[id].title}</button>`).join(''):'<p class="muted small">调查物品后，它们会出现在这里。</p>'}</div><div class="report-confirm"><small>你可以随时关闭报告，继续调查。</small><button class="primary" data-action="confirmreport" ${state.report.suspect&&state.report.weapon?'':'disabled'}>提交报告　→</button></div>`,{label:'YOUR CONCLUSION'});}
function reportPick(value){const [kind,id]=value.split(':');if(kind==='suspect'&&['daughter','butler','son','su'].includes(id)||kind==='weapon'&&state.collected.includes(id)&&C.evidence[id]?.weapon){state.report[kind]=id;save();report();}}
function submitReport(){if(!state.report.suspect||!state.report.weapon)return;closeModal();state.solved=true;state.phase='ending';state.endingStep=-1;save();render();}
function intro(){const s=C.intro[state.introStep];app.innerHTML=head('intro')+`<section class="intro-stage"><div class="row spread"><div class="eyebrow">白栎庄园 / ${s.time}</div><small>11 月 14 日</small></div><div class="stage gap"><div class="room-art room-${C.rooms[s.room].art}"></div><div class="atmosphere"></div><div class="stage-caption">${C.rooms[s.room].name}</div></div><div class="intro-dialogue">${s.person?person(s.person):''}<div class="intro-text"><div class="eyebrow">${s.person?C.people[s.person].name:state.introStep===7?'侦探':'现场'}</div><p>${s.line}</p></div>${button(state.introStep===C.intro.length-1?'开始调查 →':'继续 →','introNext','','primary')}</div><p class="intro-caption">${s.caption}</p><div class="intro-progress">${C.intro.map((_,i)=>`<span class="${i<=state.introStep?'active':''}"></span>`).join('')}</div></section>`;}
function ending(){if(state.endingStep<0){const correct=state.report.suspect==='butler'&&state.report.weapon==='bottle';app.innerHTML=head('ending')+`<section class="conclusion"><div class="eyebrow">结案报告 / 已提交</div><h2>${correct?'你的判断正确。':'这起案件，还有另一层经过。'}</h2><p>你的报告：${C.people[state.report.suspect]?.name||'—'} · ${C.evidence[state.report.weapon]?.title||'—'}</p><div class="rule"></div><p>凶手：<span class="gold">周启明</span>　　凶器：<span class="gold">棕色小瓶中的灰鸢素X</span></p><p>雨停以前，回到那场晚宴开始之前。</p>${button('进入他的视角 →','endingNext','','primary gap')}</section>`;return;}
 const s=C.ending[state.endingStep];app.innerHTML=head('ending')+`<section class="intro-stage"><div class="row spread"><div class="eyebrow">周启明 / 第一人称复盘</div><small>${state.endingStep+1} / ${C.ending.length}</small></div><div class="stage ending-stage gap"><div class="room-art room-${C.rooms[s.room].art}"></div><div class="first-person"><div class="pixel-hand"></div><div class="pixel-hand right"></div></div>${s.prop==='black'?'<div class="blackout">六点</div>':s.prop!=='hands'?`<div class="ending-prop">${art(s.prop)}</div>`:''}</div><div class="intro-dialogue"><div class="intro-text"><div class="eyebrow">${s.title}</div><p>${s.text}</p></div>${button(state.endingStep===C.ending.length-1?'尾声 →':'继续 →','endingNext','','primary')}</div></section>`;}
function conclusion(){app.innerHTML=head('ending')+`<section class="conclusion"><div class="eyebrow">CASE FILE 001 / 已归档</div><h2>未举起的酒杯</h2><div class="ending-people">${person('butler')}${person('daughter')}${person('su')}</div><p class="confession">周启明：“我以为这样，她就不用走了。”<br><span class="gold">凌知夏：“我还是会走。”</span></p><p>苏曼握住女儿的手。凌承泽没有开口。桌上的酒杯，始终没有举起。</p><div class="rule"></div><p>周启明在晚药环节投放灰鸢素X。凌维岳死亡后，凌承泽破门并刺击。两人的行为发生在不同时间。</p><p class="small muted">本案结束。记录已放入事务所的档案袋。</p><div class="row wrap gap">${button('回到事务所','returnhub','','primary')}${button('重新调查','new')}${button('重看复盘','replay')}</div></section>`;}
function help(){openModal('游玩说明',`<p>你是受邀参加晚宴的侦探。命案发生后，自由询问四位嫌疑人，调查六个房间。</p><ul class="help-list"><li>点击房间内的物品进入近景；“显示交互位置”可以标出可点击处。</li><li>与人物交谈，或向他们出示找到的物品。</li><li>物品与口供自动进入笔记。你可以并排对照、标记和写手记。</li><li>电脑和保险柜使用四位密码，线索在庄园内。</li><li>现场、药杯、水杯、药盒与棕色小瓶均完成采样后，离开办公室一次即可收到检验记录。</li><li>警犬每案可用 3 次，只寻找尚未调查的位置。</li><li>在报告中选定凶手和凶器，确认提交后进入复盘。</li></ul><p class="small muted">N：笔记　M：显示交互位置　Esc：关闭面板<br>进度保存在当前浏览器中。此 Demo 可离线游玩。<br>药物与地名均为虚构。含命案、家庭暴力的非图像化描述。</p>`,{label:'HOW TO PLAY'});}
function menu(){openModal('暂停',`<div class="file-list">${button('继续','close','','primary')}${button('游玩说明','help')}${button('返回标题','title')}${button('重新开始','new')}</div>`,{compact:true,label:'MENU'});}
const actions={
 new:()=>{if(saved)openModal('重新开始？',`<p>当前调查进度将被新的案件替换。</p><div class="row gap">${button('取消','close')}${button('重新开始','resetconfirm','','primary')}</div>`,{compact:true,label:'NEW GAME'});else startNew();},resetconfirm:startNew,
 continue:()=>{state=JSON.parse(JSON.stringify(saved));if(state.phase==='title')state.phase='hub';closeModal();render();},
 title:()=>{closeModal();state.phase='title';render();},menu,help,close:closeModal,notebook:()=>notebook(),notetab:notebook,noteitem:id=>inspect(id,'notebook'),room:goRoom,spot:visitSpot,inspect:id=>inspect(id),
 inspectback:v=>{if(v==='notebook')notebook();else closeModal();},
 star:id=>{state.stars=state.stars.includes(id)?state.stars.filter(x=>x!==id):[...state.stars,id];save();const star=overlayRoot.querySelector('[data-action="star"]');if(star)star.textContent=state.stars.includes(id)?'★ 已标记':'☆ 标记';},
 zoom:id=>openModal(C.evidence[id]?.title||'物品近景',`<div class="zoom-image">${art(id)}</div><div class="row gap">${button('返回物品记录','inspect',id)}${button('物品对照','notetab','compare')}</div>`,{wide:true,label:'CLOSE UP'}),
 hotspots:()=>{showSpots=!showSpots;render();},leaves:()=>inspect('bottle'),talk,ask,showevidence:showEvidence,dog,report,reportpick:reportPick,
 confirmreport:()=>openModal('确认提交？',`<p>提交后将显示答案，并进入案件复盘。</p><p class="gap gold">${C.people[state.report.suspect].name} · ${C.evidence[state.report.weapon].title}</p><div class="row gap">${button('继续调查','close')}${button('确认提交','submitreport','','primary')}</div>`,{compact:true,label:'FINAL REPORT'}),submitreport:submitReport,
 invitationmail:()=>openModal('一封私人邀请',`<div class="eyebrow">凌维岳 / 致侦探</div><p class="gap">上次展品的事，多谢。11月14日晚七点，来白栎庄园坐坐。有些事情，也想请您做个见证。</p><p class="gap muted">—— 凌维岳</p>${button('赴约 →','accept','','primary gap')}`,{compact:true,label:'INBOX / 01'}),
 accept:()=>{closeModal();state.phase='intro';state.introStep=0;save();render();},
 news:()=>openModal('鹭湾晚报',`<div class="eyebrow">2026.11.14</div><h3 class="gap">凌氏基金宣布扩大助学计划</h3><p class="gap">凌氏实业创办人凌维岳将于近日出席年度答谢活动。基金称，新一期计划将向当地学校开放申请。</p><p class="small muted gap">今晚鹭湾持续有雨，出行请带好雨具。</p>`,{compact:true,label:'NEWS'}),
 pet:()=>{closeModal();toast('它轻轻蹭了蹭你的手。');},
 introNext:()=>{state.introStep++;if(state.introStep>=C.intro.length){state.phase='investigation';state.room='office';}save();render();},
 endingNext:()=>{state.endingStep++;if(state.endingStep>=C.ending.length)state.phase='closed';save();render();},
 returnhub:()=>{state.phase='hub';save();render();},caseconclusion:()=>{closeModal();state.phase='closed';save();render();},replay:()=>{closeModal();state.phase='ending';state.endingStep=0;save();render();}
};
document.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(b&&!b.disabled&&actions[b.dataset.action])actions[b.dataset.action](b.dataset.value||'');});
document.addEventListener('submit',e=>{if(e.target.matches('.password-form')){e.preventDefault();unlock(e.target);}});
document.addEventListener('input',e=>{if(e.target.id==='personal-notes'){state.notes=e.target.value;save();}if(e.target.matches('.password-display'))e.target.value=e.target.value.replace(/\D/g,'');});
document.addEventListener('change',e=>{if(e.target.dataset.compare){if(e.target.dataset.compare==='a')compareA=e.target.value;else compareB=e.target.value;notebook('compare');}});
document.addEventListener('dragstart',e=>{const el=e.target.closest('[draggable="true"]');if(el){e.dataTransfer.setData('text/plain',el.dataset.value);e.dataTransfer.effectAllowed='copy';}});
document.addEventListener('dragover',e=>{const el=e.target.closest('[data-slot]');if(el){e.preventDefault();el.classList.add('over');}});
document.addEventListener('dragleave',e=>e.target.closest('[data-slot]')?.classList.remove('over'));
document.addEventListener('drop',e=>{const el=e.target.closest('[data-slot]');if(!el)return;e.preventDefault();el.classList.remove('over');const v=e.dataTransfer.getData('text/plain');if(v.split(':')[0]===el.dataset.slot)reportPick(v);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();return;}if(overlay&&e.key==='Tab'){const list=[...overlayRoot.querySelectorAll('button:not(:disabled),input,textarea,select')];if(!list.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}if(e.target.matches('input,textarea,select')||overlay)return;if(state.phase==='investigation'){if(e.key.toLowerCase()==='n')notebook();if(e.key.toLowerCase()==='m')actions.hotspots();}if((state.phase==='intro'||state.phase==='ending')&&e.code==='Space'){e.preventDefault();state.phase==='intro'?actions.introNext():actions.endingNext();}});
state.phase='title';render();
})();
